# Generated by Django 2.2.12 on 2020-05-09 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokecode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pannel',
            name='image',
            field=models.ImageField(upload_to='static/pokecode/images'),
        ),
        migrations.AlterField(
            model_name='pannel',
            name='music',
            field=models.FileField(upload_to='static/pokecode/musics'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('falsees', models.ManyToManyField(to='pokecode.Pannel')),
                ('true', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Card', to='pokecode.Pannel')),
            ],
        ),
    ]
